<?php

namespace vaersaagod\aimate\models;

use craft\base\ElementInterface;
use craft\base\Model;
use craft\helpers\StringHelper;

use Illuminate\Support\Collection;

use vaersaagod\aimate\AIMate;
use vaersaagod\aimate\helpers\OpenAiHelper;

class Prompt extends Model
{

    /** @var string|null The input text, if any */
    public ?string $text = null;

    /** @var ElementInterface|null */
    public ?ElementInterface $element = null;

    /** @var PromptConfig */
    private PromptConfig $config;

    /** @var string */
    private string $directives = '';

    /**
     * @return array
     */
    public function rules(): array
    {
        $rules = parent::rules();
        $rules[] = ['text', 'required', 'when' => static fn(Prompt $prompt) => !$prompt->config->getAllowBlank()];
        return $rules;
    }

    /**
     * @param $attributeNames
     * @param $clearErrors
     * @return bool
     */
    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getHandle(): string
    {
        return $this->config->handle;
    }

    /**
     * @return string
     * @throws \Throwable
     * @throws \yii\base\Exception
     */
    public function getPrompt(): string
    {
        // Get template
        $template = $this->config->template;

        // Replace text tokens
        $template = str_replace('<text>', $this->text ?? '', $template);

        // Render the prompt as an object template, in case we have an element
        $prompt = \Craft::$app->getView()->renderObjectTemplate($template, $this->element);

        return $prompt;
    }

    /**
     * @param PromptConfig $config
     * @return void
     */
    public function setConfig(PromptConfig $config): void
    {
        $this->config = $config;
    }

    /**
     * @return bool
     */
    public function getIsHtml(): bool
    {
        return StringHelper::isHtml($this->text ?? '') || StringHelper::isHtml($this->template ?? '');
    }

    /**
     * @return int|null
     */
    public function getMaxWords(): ?int
    {
        $maxWords = $this->config->maxWords;

        if (empty($maxWords) && $maxWords !== false && !empty($this->text)) {
            $maxWords = StringHelper::countWords($this->text);
        }

        if (!$maxWords) {
            return null;
        }

        $multiplier = $this->config->maxWordsMultiplier ?? AIMate::getInstance()->getSettings()->maxWordsMultiplier;

        if (!empty($multiplier)) {
            return round($maxWords * $multiplier);
        }

        return $maxWords;
    }

    /**
     * @return string
     */
    public function getModel(): string
    {
        return $this->config->model ?? AIMate::getInstance()->getSettings()->model;
    }

    /**
     * @return float
     */
    public function getTemperature(): float
    {
        return $this->config->temperature ?? AIMate::getInstance()->getSettings()->temperature ?? 0.7;
    }

    /**
     * @return string|null
     * @throws \Throwable
     * @throws \yii\base\Exception
     */
    public function complete(): ?string
    {
        $client = OpenAiHelper::getClient();

        $prompt = $this->getPrompt();
        $language = $this->element?->getSite()->language ?? \Craft::$app->getSites()->getCurrentSite()->language;

        $systemPrompt = <<<EOT
You are a web editor for a website CMS.
Write and edit content to be clear, concise, user-focused, SEO-friendly, and publication-ready.
Improve structure, readability, and accuracy while preserving meaning and brand tone.
Do not invent facts or add marketing claims unless instructed.
- When asked to rewrite or correct text, do so in a way that is clear and concise.
- When asked to rewrite or correct text, you keep the length of the result close to the original.
- When asked to rewrite or correct text, you keep the punctation at the end of the text the same as the original.
- Return output in valid JSON format exactly as specified.
EOT;

        $rules = [
           "Make sure the returned text is in the correct language.",
            ...$this->config->rules ?? []
        ];

        // Figure out the max number of words we want
        $maxWords = $this->getMaxWords();
        if ($maxWords) {
            $rules[] = "In about $maxWords words or less.";
        }

        // Retain HTML?
        if ($this->getIsHtml()) {
            $rules[] = 'Preserve HTML tags.';
        }
        
        $userPrompt = [
            "role" => "user",
            "content" => [
                [
                    "type" => "text",
                    "text" => json_encode([
                        "language" => $language,
                        "context" => '',
                        "output_format" => [
                            "text" => "string",
                            "confidence" => "float 0–1",
                            "warnings" => "array of strings",
                            "language" => $language
                        ],
                        "rules" => $rules
                    ], JSON_THROW_ON_ERROR | JSON_PRETTY_PRINT)
                ],
                [
                    "type" => "text",
                    'text' => $prompt
                ]
            ]
        ];

        $messages = [
            [
                "role" => "system",
                "content" => $systemPrompt
            ],
            $userPrompt
        ];

        $params = [
            'model' => $this->getModel(),
            'messages' => $messages,
        ];

        $result = $client->chat()->create($params);

        $response = Collection::make($result['choices'] ?? [])->first(static fn(array $choice) => $choice['finish_reason'] === 'stop' && !empty($choice['message']['content'] ?? null));

        if (!$response) {
            \Craft::error('No response from AI for prompt ' . $prompt . ': ' . print_r($response, true), __METHOD__);
            return null;
        }

        $message = trim($response['message']['content']);

        try {
            $data = json_decode($message, true, 512, JSON_THROW_ON_ERROR);
        } catch (\Throwable $e) {
            \Craft::error('Invalid JSON response from AI for prompt ' . $prompt . ': ' . $e->getMessage(), __METHOD__);
            return null;
        }

        if (!isset($data['text'])) {
            return null;
        }

        return trim($data['text']);
    }

}
